import { Camera, type Point } from "./Camera";
import type { Stroke } from "./Stroke";
import { getWorldTimeProgress, type MapType, type TimeOfDay } from "../domain";
export interface Brush { color:string; size:number; eraser:boolean; }
export interface SurfaceOptions { worldWidth:number; worldHeight:number; map:MapType; time:TimeOfDay; round?:number; }
const EXPORT_MAX_WIDTH=1800, EXPORT_MAX_HEIGHT=2400;
export class DrawingSurface {
 readonly camera:Camera; private readonly worldBackgroundCanvas:HTMLCanvasElement; private readonly worldBackgroundContext:CanvasRenderingContext2D; private readonly baseCanvas:HTMLCanvasElement; private readonly baseContext:CanvasRenderingContext2D; private readonly strokeCanvas:HTMLCanvasElement; private readonly strokeContext:CanvasRenderingContext2D; private readonly viewportContext:CanvasRenderingContext2D;
 private cssWidth=1; private cssHeight=1; private dpr=1; private canvasLeft=0; private canvasTop=0; private canvasRectWidth=1; private canvasRectHeight=1; private lastPoint:Point|null=null; private livePoints:Point[]=[]; private liveBrush:Brush|null=null; private renderFrame:number|null=null; private destroyed=false;
 constructor(private readonly viewportCanvas:HTMLCanvasElement,private readonly options:SurfaceOptions){const context=viewportCanvas.getContext("2d");if(!context)throw new Error("無法建立 viewport context");this.viewportContext=context;this.worldBackgroundCanvas=this.createWorldCanvas();const bg=this.worldBackgroundCanvas.getContext("2d");if(!bg)throw new Error("無法建立世界背景 context");this.worldBackgroundContext=bg;this.baseCanvas=this.createWorldCanvas();const base=this.baseCanvas.getContext("2d");if(!base)throw new Error("無法建立 base context");this.baseContext=base;this.strokeCanvas=this.createWorldCanvas();const stroke=this.strokeCanvas.getContext("2d");if(!stroke)throw new Error("無法建立 stroke context");this.strokeContext=stroke;this.paintWorldBackground();this.camera=new Camera({width:options.worldWidth,height:options.worldHeight});}
 resize(cssWidth:number,cssHeight:number):void{if(!Number.isFinite(cssWidth)||!Number.isFinite(cssHeight)||cssWidth<=0||cssHeight<=0)return;this.cancelRender();this.cssWidth=Math.max(1,Math.round(cssWidth));this.cssHeight=Math.max(1,Math.round(cssHeight));this.dpr=Math.max(1,Math.min(window.devicePixelRatio||1,2));this.viewportCanvas.style.width=`${this.cssWidth}px`;this.viewportCanvas.style.height=`${this.cssHeight}px`;this.refreshCanvasRect();const w=Math.max(1,Math.round(this.cssWidth*this.dpr)),h=Math.max(1,Math.round(this.cssHeight*this.dpr));if(this.viewportCanvas.width!==w)this.viewportCanvas.width=w;if(this.viewportCanvas.height!==h)this.viewportCanvas.height=h;this.camera.setViewport(this.cssWidth,this.cssHeight);this.render();}
 eventToScreen(event:PointerEvent|WheelEvent,refreshLayout=false):Point{if(refreshLayout)this.refreshCanvasRect();return{x:(event.clientX-this.canvasLeft)*this.cssWidth/this.canvasRectWidth,y:(event.clientY-this.canvasTop)*this.cssHeight/this.canvasRectHeight};}
 eventToWorld(event:PointerEvent,refreshLayout=false):Point{return this.camera.screenToWorld(this.eventToScreen(event,refreshLayout));}
 startStroke(point:Point,brush:Brush):boolean{if(!this.camera.isInsideWorld(point))return false;this.lastPoint=point;this.livePoints=[point];this.liveBrush={...brush};this.beginLiveViewport(brush);this.drawDotToViewport(point,brush);return true;}
 continueStroke(point:Point,brush:Brush):void{if(!this.lastPoint)return;const from=this.lastPoint;this.lastPoint=point;this.livePoints.push(point);this.drawLiveSegment(from,point,brush);}
 endStroke():void{if(this.lastPoint&&this.livePoints.length>0&&this.liveBrush)this.commitLiveStroke();this.lastPoint=null;this.livePoints=[];this.liveBrush=null;this.resetViewportTransform();this.cancelRender();this.render();}
 clear():void{this.endStroke();this.strokeContext.clearRect(0,0,this.options.worldWidth,this.options.worldHeight);this.render();}
 redraw(strokes:readonly Stroke[]):void{this.endStroke();this.strokeContext.clearRect(0,0,this.options.worldWidth,this.options.worldHeight);for(const stroke of strokes)this.drawStroke(stroke);this.render();}
 async loadImage(source:string):Promise<void>{const image=new Image();image.decoding="async";await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error("上一頁圖片載入失敗"));image.src=source;});this.endStroke();this.baseContext.clearRect(0,0,this.options.worldWidth,this.options.worldHeight);this.baseContext.drawImage(image,0,0,this.options.worldWidth,this.options.worldHeight);this.render();}
 render():void{if(this.destroyed)return;const ctx=this.viewportContext,dpr=this.dpr,zoom=this.camera.zoom;ctx.globalCompositeOperation="source-over";ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,this.cssWidth,this.cssHeight);ctx.fillStyle=this.options.map==="space"?"#030711":"#d8e1dc";ctx.fillRect(0,0,this.cssWidth,this.cssHeight);ctx.save();ctx.beginPath();ctx.rect(0,0,this.cssWidth,this.cssHeight);ctx.clip();ctx.setTransform(dpr*zoom,0,0,dpr*zoom,-this.camera.x*dpr*zoom,-this.camera.y*dpr*zoom);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="medium";ctx.drawImage(this.worldBackgroundCanvas,0,0);ctx.drawImage(this.baseCanvas,0,0);ctx.drawImage(this.strokeCanvas,0,0);ctx.restore();ctx.setTransform(1,0,0,1,0,0);}
 requestRender():void{if(this.destroyed||this.renderFrame!==null)return;this.renderFrame=window.requestAnimationFrame(()=>{this.renderFrame=null;this.render();});}
 destroy():void{this.destroyed=true;this.lastPoint=null;this.livePoints=[];this.liveBrush=null;this.cancelRender();}
 getStrokeCoverageScore():number{const step=6,w=this.options.worldWidth,h=this.options.worldHeight,pixels=this.strokeContext.getImageData(0,0,w,h).data;let occupied=0,sampled=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){sampled++;if(pixels[(y*w+x)*4+3]>24)occupied++;}if(!occupied||!sampled)return 0;return Math.max(1,Math.min(100,Math.round(Math.sqrt(occupied/sampled)*100)));}
 exportPng():string{this.endStroke();const scale=Math.min(1,EXPORT_MAX_WIDTH/this.options.worldWidth,EXPORT_MAX_HEIGHT/this.options.worldHeight),width=Math.max(1,Math.round(this.options.worldWidth*scale)),height=Math.max(1,Math.round(this.options.worldHeight*scale));const output=document.createElement("canvas");output.width=width;output.height=height;const ctx=output.getContext("2d");if(!ctx)throw new Error("無法建立輸出畫布");ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.clearRect(0,0,width,height);ctx.drawImage(this.worldBackgroundCanvas,0,0,width,height);ctx.drawImage(this.baseCanvas,0,0,width,height);ctx.drawImage(this.strokeCanvas,0,0,width,height);return output.toDataURL("image/png");}
 private createWorldCanvas():HTMLCanvasElement{const canvas=document.createElement("canvas");canvas.width=this.options.worldWidth;canvas.height=this.options.worldHeight;return canvas;}
 private paintWorldBackground():void{const ctx=this.worldBackgroundContext,w=this.options.worldWidth,h=this.options.worldHeight,p=getWorldTimeProgress(this.options.round??1);ctx.clearRect(0,0,w,h);ctx.globalCompositeOperation="source-over";if(this.options.map==="space")this.paintSpaceBackground(ctx,w,h,p);else this.paintEarthBackground(ctx,w,h,p);}
 private paintEarthBackground(ctx:CanvasRenderingContext2D,w:number,h:number,p:number):void{const day={r:118,g:204,b:244},dusk={r:238,g:142,b:110},night={r:20,g:31,b:67};const top=this.color(day,dusk,Math.min(1,p*2));const bottom=this.color({r:218,g:244,b:255},night,Math.max(0,(p-.35)/.65));const gradient=ctx.createLinearGradient(0,0,0,h);gradient.addColorStop(0,top);gradient.addColorStop(.68,bottom);gradient.addColorStop(1,p<.65?"#6d8b72":"#182b35");ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);const horizon=h*.78,ground=ctx.createLinearGradient(0,horizon,0,h);ground.addColorStop(0,p<.6?"rgba(67,104,73,.35)":"rgba(8,22,30,.6)");ground.addColorStop(1,p<.6?"rgba(22,55,48,.8)":"rgba(4,12,20,.95)");ctx.fillStyle=ground;ctx.fillRect(0,horizon,w,h-horizon);const x=w*(.12+p*.76),y=h*(.34-Math.sin(p*Math.PI)*.2),nightMode=p>=.67;ctx.globalAlpha=nightMode?.9:.95;ctx.fillStyle=nightMode?"#f3f4c7":"#fff1a8";ctx.shadowBlur=nightMode?28:42;ctx.shadowColor=nightMode?"rgba(225,235,190,.7)":"rgba(255,214,91,.8)";ctx.beginPath();ctx.arc(x,y,nightMode?w*.035:w*.045,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.globalAlpha=1;if(p>.58)this.paintStars(ctx,w,h,p);}
 private paintSpaceBackground(ctx:CanvasRenderingContext2D,w:number,h:number,p:number):void{const phase=p<.5?p*2:1,gradient=ctx.createRadialGradient(w*.48,h*.38,10,w*.5,h*.45,Math.max(w,h)*.8);gradient.addColorStop(0,p<.55?"#203d70":"#25184b");gradient.addColorStop(.55,p<.55?"#0d1b4b":"#100b2b");gradient.addColorStop(1,"#02040c");ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.14+phase*.08;const nebula=ctx.createRadialGradient(w*.22,h*.68,10,w*.22,h*.68,w*.65);nebula.addColorStop(0,p<.5?"#6bd5ff":"#d59cff");nebula.addColorStop(1,"transparent");ctx.fillStyle=nebula;ctx.fillRect(0,0,w,h);ctx.globalAlpha=1;this.paintStars(ctx,w,h,Math.max(.45,p));}
 private paintStars(ctx:CanvasRenderingContext2D,w:number,h:number,p:number):void{const count=Math.round(55+p*45);ctx.fillStyle="rgba(255,255,255,.78)";for(let i=0;i<count;i++){const x=(i*137.5)%w,y=(i*83.7+31)%(h*.74),r=1+((i*17)%10)/10;ctx.globalAlpha=.25+((i*29)%70)/100;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
 private color(a:{r:number;g:number;b:number},b:{r:number;g:number;b:number},amount:number):string{const t=Math.max(0,Math.min(1,amount)),r=Math.round(a.r+(b.r-a.r)*t),g=Math.round(a.g+(b.g-a.g)*t),v=Math.round(a.b+(b.b-a.b)*t);return`rgb(${r}, ${g}, ${v})`;}
 private refreshCanvasRect():void{const rect=this.viewportCanvas.getBoundingClientRect();this.canvasLeft=rect.left;this.canvasTop=rect.top;this.canvasRectWidth=Math.max(1,rect.width);this.canvasRectHeight=Math.max(1,rect.height);}
 private beginLiveViewport(brush:Brush):void{const ctx=this.viewportContext;ctx.globalCompositeOperation=brush.eraser?"destination-out":"source-over";ctx.setTransform(this.dpr*this.camera.zoom,0,0,this.dpr*this.camera.zoom,-this.camera.x*this.dpr*this.camera.zoom,-this.camera.y*this.dpr*this.camera.zoom);this.configureBrush(ctx,brush);}
 private drawDotToViewport(point:Point,brush:Brush):void{const ctx=this.viewportContext;ctx.beginPath();ctx.arc(point.x,point.y,Math.max(brush.size/2,.5),0,Math.PI*2);ctx.fill();}
 private drawLiveSegment(from:Point,to:Point,brush:Brush):void{const ctx=this.viewportContext;ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();if(brush.eraser)this.drawSegment(this.strokeContext,from,to,brush);}
 private commitLiveStroke():void{const brush=this.liveBrush;if(!brush||brush.eraser)return;const first=this.livePoints[0];if(!first)return;this.configureBrush(this.strokeContext,brush);this.strokeContext.beginPath();this.strokeContext.moveTo(first.x,first.y);for(let i=1;i<this.livePoints.length;i++)this.strokeContext.lineTo(this.livePoints[i].x,this.livePoints[i].y);this.strokeContext.stroke();this.drawDot(this.strokeContext,first,brush);}
 private drawStroke(stroke:Stroke):void{const[first,...rest]=stroke.points;if(!first)return;this.drawDot(this.strokeContext,first,stroke.brush);if(rest.length===0)return;this.configureBrush(this.strokeContext,stroke.brush);this.strokeContext.beginPath();this.strokeContext.moveTo(first.x,first.y);for(const point of rest)this.strokeContext.lineTo(point.x,point.y);this.strokeContext.stroke();}
 private drawSegment(ctx:CanvasRenderingContext2D,from:Point,to:Point,brush:Brush):void{this.configureBrush(ctx,brush);ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();}
 private drawDot(ctx:CanvasRenderingContext2D,point:Point,brush:Brush):void{this.configureBrush(ctx,brush);ctx.beginPath();ctx.arc(point.x,point.y,Math.max(brush.size/2,.5),0,Math.PI*2);ctx.fill();}
 private configureBrush(ctx:CanvasRenderingContext2D,brush:Brush):void{ctx.globalCompositeOperation=brush.eraser?"destination-out":"source-over";ctx.strokeStyle=brush.color;ctx.fillStyle=brush.color;ctx.lineWidth=brush.size;ctx.lineCap="round";ctx.lineJoin="round";}
 private resetViewportTransform():void{this.viewportContext.globalCompositeOperation="source-over";this.viewportContext.setTransform(1,0,0,1,0,0);}
 private cancelRender():void{if(this.renderFrame===null)return;window.cancelAnimationFrame(this.renderFrame);this.renderFrame=null;}
}